version: "3.8"
services:
  backend:
    build: .
    restart: always
    container_name: shortener_b
    command: bash -c "alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0"
    volumes:
      - ./project:/project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - shortener
  test_smtp:
    image: mailhog/mailhog
    container_name: test_smtp
    restart: always
    ports:
      - "8025:8025"
    networks:
      - shortener
  db:
    image: postgres:9.6-alpine
    container_name: shortener_db
    volumes:
      - shortener-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - shortener

volumes:
  shortener-pgdata:

networks:
  shortener:
